[package]
name = "ownable"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = { version = "0.30.1", features = ["init-if-needed" ] }
ownable-macro = { version = "0.1.0", path = "../ownable-macro" }
